### ISSUE TITLE
"Than" must have word following

### ISSUE THREAD

**Issue by 01mf02** [Automattic/harper#131]
Consider the sentence:

> More often than, we cannot foresee the of our community.

Harper currently does not find anything wrong with this sentence.
Yet, the word "than" must be followed by a word, and the word "the" must be followed by an adjective or a noun (I believe).
It would be cool if Harper could diagnose these mistakes.

**Comment by elijah-potter** [comment]
Thanks for the feedback! I've got a linter working for the first issue, and am working on one for the second issue. It should be available in the most recent release. Feel free to give it a whirl and let me know if you find any problems.

**Comment by elijah-potter** [comment]
It looks like this has been resolved. If that isn't the case, feel free to reopen the issue.

**Comment by 01mf02** [comment]
Just tried it on https://writewithharper.com/, and the issue persists there.

**Comment by elijah-potter** [comment]
It turns out it was still happening on the website due to a bug specific to that target. It should be resolved now (you may have to clear your cache).

Thanks again for letting me know!

**Comment by 01mf02** [comment]
Now the "than" error is detected, but not the "the of".

**Comment by hippietrail** [comment]
Adverbs can also follow "the" because they can modify adjectives: "**The extremely** fat man".

Also don't forget that verbs behave as nouns in their gerund form and as adjectives in their present participle form, both of which share the -ing inflection: "**The running** of the bull", "**The running** man".

**Comment by hippietrail** [comment]
To me a counterexample is "He is 7 foot tall so he's the only one I'm shorter than".

But even though it sounds right to my native-speaker intuition, I went ahead and asked on my usual English forum: [Is it correct to end a sentence with "than"?](https://english.stackexchange.com/questions/629292/is-it-correct-to-end-a-sentence-with-than)
