### ISSUE TITLE
Browser textarea lint highlighting broken when scrolling: lints don't scroll away, new lints don't show up at all.

### ISSUE THREAD

**Issue by laundmo** [Automattic/harper#1472]
**Describe the bug**
A simple textarea element after scrolling due to overflow doesn't render lint underlines correctly.
It keeps the underlines/boxes from before scrolling, showing them over unrelated text, and doesn't show anything for errors newly scrolled into view.

Note: While the easiest reproduction is a simple textarea, this same issue also happens on GitHub (one of the advertised working sites) when a scroll happens. (happened to me while writing this.)

**To Reproduce**

1. Open a HTML document with a basic textarea element like:
    ```html
    <!DOCTYPE html>
    <html>
      <body>
        <textarea rows="5" cols="33"></textarea>
      </body>
    </html> 
    ```
    rendered version: https://share.yadamiel.com/basic_textarea.html
2. <details><summary>Paste a long text with a misspelled word at the start</summary>
    <p>
    
    ```
    thas iss an loong txt.
    This is a long text.
    This is a long text.
    This is a long text.
    This is a long text.
    This is a long text.
    This is a long text.
    This is a long text.
    Sum othr mispeled sentnce.
    ```
    
    </p>
    </details> 
3. Scroll down to see the end
4. Notice how the lint highlight stays in-place even though you've scrolled away.

**Expected behavior**
I expected the lint highlight to scroll away with the text its supposed to be attached to, ending up hidden offscreen.
I expected newly visible errors to be highlighted.

**Screenshots**

![Image](https://github.com/user-attachments/assets/db95ef06-2c7e-41f1-baa8-480515c895ac)

**Platform**
Firefox, Chromium-based

I only tested on my daily driver Firefox with lots of extensions. For the Chromium-based browser i used a blank instance of Thorium.

**Additional context**
It seems to be related to the way highlights are rendered: they are added to a new div, which is overlayed on top of the textarea and into which the highlights are placed with style: `position: fixed; left: 10px; top: 11px;` (one example). This does not seem to get updated on scroll, and the positions are not otherwise tied to the underlying textarea.

Prior work which i found that seems to handle scroll (and has a compatible license):
- native/minority language checker (ISC license in package.json): https://github.com/divvun/divvun-gramcheck-webextension/blob/5c78e13180f9af2d00976201e7f8de1bb5a72575/src/content/overlay-manager.ts#L691
- Korean language checker for a specific browser (MIT): https://github.com/grammar-team/whale-grammar/blob/25480276c2b2d086d6daf392bf34004d2fae5e65/src/js/inspection_components/grammar-mirror.functions.js#L100

**Comment by elijah-potter** [comment]
I believe the scrolling issue should be solved. Can you confirm @laundmo?

**Comment by laundmo** [comment]
After verifying I had the newest version 0.47, I found that while its fixed on Chromium-based browsers, on Firefox its still broken with the same issues.
