### ISSUE TITLE
repeated word rule doesn't fire

### ISSUE THREAD

**Issue by notuntoward** [Automattic/harper#253]
Repeated words aren't detected, although I have this rule turned on.  Below, "accurate" is repeated.

![image](https://github.com/user-attachments/assets/dc97b292-21f0-4e33-a82b-44709b7e5ad6)

![image](https://github.com/user-attachments/assets/9b7c3297-2192-4b97-a5c3-6ca5f5b17709)

**Comment by elijah-potter** [comment]
Hey @notuntoward,

Sorry for the delay in getting back to you on this. Things have been a little hectic.

We've just [released Harper `v0.13.0`](https://github.com/Automattic/harper/releases/tag/v0.13.0), which incorporates some significant improvements to this rule, thanks to @grantlemons. 
Would you mind testing to make sure you don't get any more false-negatives like this so we can close issue?

**Comment by notuntoward** [comment]
@elijah-potter , Thanks.  Unfortunately, it still doesn't work for me in this example:

> this paper shows that, while the method may be more accurate accurate, the turnout overestimate suggests that self-selection bias is not sufficiently reduced.

"accurate" is typed twice but the repetition isn't detected.  

But I should note that I had difficulties updating -- the install procedure stalled on Harper.  When I restarted obsidian, then I got a message saying something like "Harper cannot be restarted," After uninstall and then reinstall, Harper did restart, and appeared to be the newest version (1.3.0).  But maybe it's not, really?

**Comment by grantlemons** [comment]
Ah, the obsidian plugin seemed to have had a large problem on 0.13.0 (#338), but @elijah-potter has pushed out 0.14.0 which should hopefully resolve the issue.

In my local tests I found that harper linted your example correctly, so if you update the obsidian plugin to the 0.14.0 version, it will probably work as intended.

**Comment by elijah-potter** [comment]
@notuntoward, would you mind confirming that the issue has been fixed on your end so we can close it out? Thanks again for letting us know about it!

**Comment by notuntoward** [comment]
With 0.15.0, it still doesn't detect the repeat.  This is on Obsidian.

**Comment by elijah-potter** [comment]
Hmm, that's odd. I'm not able to replicate your issue. Are you by chance on MacOS? Would you mind opening the developer tools and giving us a screenshot of any errors you see in the "Console" tab? To do that, you can press `cmd + option+i` on MacOS or `ctrl + shift + i` otherwise.

Here's what it looks like on my system.

![What it looks like on my system.](https://github.com/user-attachments/assets/d660a423-ec8a-4364-a551-236aa92ce233)

**Comment by hippietrail** [comment]
Note that in many languages including Indonesian and Malay reduplication is part of the grammar. I'm not sure how far off Harper is from supporting more human languages though but worth keeping in mind.

**Comment by elijah-potter** [comment]
@hippietrail, this is something to consider when the time comes. When we set up multilingual support, we'll go through and make new rules (likely by copying the existing ones and modifying them where necessary).

**Comment by grantlemons** [comment]
Different languages would have different associated lints, so it's not too much of a concern here. As for language support, theoretically we can extend the core to allow for more languages, but english is currently assumed so many places that the actual change would be quite the undertaking.

**Comment by elijah-potter** [comment]
I'm going to take that as a no.
